// Generated by scripts/sync-defaults.mjs from the extension's content.js. Do not edit by hand.
export const DEFAULT_TEMPLATES = {
  "callcenter": {
    "subject": "who's answering when {{company}} is {{hours_gap}}?",
    "body": "Hi {{company}} team,\n\nDid a little snooping: you're {{hours_gap}}. Fair enough, everyone deserves a life.\n\nThe phone doesn't clock off when you do, though. For {{business_type}}, the calls that come in after hours are rarely the boring ones. {{pain}}\n\nWe fix that. Our people pick up as your team, day or night: they book what can be booked, flag what's urgent, and send you a tidy summary in the morning. About $6-10/hr, no hiring, no payroll, no drama.\n\nWant to try it for a week and see what you've been missing?\n\n{{sender_name}}\nZemenay"
  },
  "callcenter-generic": {
    "subject": "honest question, {{company}}: who picks up when you're slammed?",
    "body": "Hi {{company}} team,\n\nHonest question: what happens to your phone when everyone's busy with actual customers?\n\nFor {{business_type}}, a missed call is rarely a small one. {{pain}}\n\nWe fix that. Our people pick up as your team, book what can be booked, flag what's urgent, and send you a tidy summary. About $6-10/hr, no hiring, no payroll, no drama.\n\nWant to try it for a week and count the calls you'd have missed?\n\n{{sender_name}}\nZemenay"
  },
  "tech": {
    "subject": "{{company}}, senior devs without the recruiter tax?",
    "body": "Hi {{company}} team,\n\nGuessing {{company}} has more client work than hands right now. If so: {{pain}}\n\nWe've got vetted senior devs (React, Node, Python, React Native, DevOps) who can start in about two weeks. Contract, zero placement fee, and we handle payroll and compliance. You just get the work shipped.\n\nWant me to send two or three profiles? Worst case, you've looked at some very nice CVs.\n\n{{sender_name}}\nZemenay"
  },
  "va": {
    "subject": "{{company}}, who's doing your admin at 9pm?",
    "body": "Hi {{company}} team,\n\nBet nobody at {{company}} got into this business to spend their evenings on admin. And yet: {{pain}}\n\nWe'll give you a dedicated virtual assistant who takes all of that off your plate: inbox, calendar, bookings, reminders, data entry, chasing suppliers. They work your hours and learn your systems. $6-10/hr, month to month, walk away whenever.\n\nWant to see what their first month would look like?\n\n{{sender_name}}\nZemenay"
  },
  "followup": {
    "subject": "still thinking it over, {{company}}?",
    "body": "Hi {{company}} team,\n\nFollowing up on my note from last week, in case it got buried. (It happens. Honestly, that's sort of our whole point.)\n\nShort version: we take the calls, the admin or the dev work you don't have hands for, from about $6-10/hr, with no hiring and no payroll on your side.\n\nWorth a quick 15-minute call? If it's a no, just reply \"no\" and I'll leave you alone. Promise.\n\n{{sender_name}}\nZemenay"
  }
};
